test:
	clear;
	gcc -g -std='c99' -fgnu89-inline -fdiagnostics-color=always *.c -o ./out/result; 
	./out/result

clean:
	rm ./out/result;

# format_test:
# 	clear;
# 	gcc -g -std='c99' -fgnu89-inline -fdiagnostics-color=always *.c -o ./out/result; 
# 	# valgrind ./out/result
# 	./out/result

# normal_test:*.c
# 	gcc -g -fgnu89-inline -fdiagnostics-color=always *.c -o ./out/result; 
# 	./out/result

# clean:
# 	# rm ./out/myfile.bin;
# 	rm ./out/result;